version: "3.3"
services:
  web:
    build: ./cryptotrac
    command: gunicorn cryptotrac.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # - static:/app/static
      # - Assets:/app/Assets
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static:/app/static
  redis:
    image: redis:alpine
    depends_on:
      - web
    expose:
      - 6379
    ports:
      - 6379:6379
  celery:
    image: celery:3.1
    depends_on:
      - redis
      - web
    build:
      context: ./cryptotrac
    command: celery -A cryptotrac.celery worker -l info
    volumes:
      # - static:/app/static
    env_file:
      - ./.env
    restart: always

volumes:
  static:    
  Assets:
